# Generated by Django 5.2.1 on 2025-05-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=15)),
                ('year', models.CharField(choices=[('1st year', '1st year'), ('2st year', '2st year'), ('3st year', '3st year'), ('4st year', '4st year')])),
                ('branch', models.CharField(choices=[('CSE-AIML', 'CSE-AIML'), ('AI & DS', 'AI & DS'), ('ISE', 'ISE'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('ETE', 'ETE'), ('EIE', 'EIE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('BIOTECH', 'BIOTECH'), ('CHEMICAL', 'CHEMICAL'), ('IEM', 'IEM')])),
            ],
        ),
    ]
