# Generated by Django 5.2.1 on 2025-05-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('authorid', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('bookname', models.CharField(max_length=100)),
                ('bookid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='bookauthor',
            fields=[
                ('pk', models.CompositePrimaryKey('bookid', 'authorid', blank=True, editable=False, primary_key=True, serialize=False)),
                ('authorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='members.author')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='members.books')),
            ],
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_usn', to='members.members')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_review', to='members.books')),
            ],
        ),
        migrations.CreateModel(
            name='bookurl',
            fields=[
                ('bookurl', models.URLField()),
                ('pk', models.CompositePrimaryKey('bookid', 'bookurl', blank=True, editable=False, primary_key=True, serialize=False)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book2', to='members.books')),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog2', to='members.blogs')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='members.members')),
            ],
        ),
        migrations.CreateModel(
            name='dislikes',
            fields=[
                ('pk', models.CompositePrimaryKey('usn', 'blogs', blank=True, editable=False, primary_key=True, serialize=False)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs3', to='members.blogs')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members3', to='members.members')),
            ],
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('pk', models.CompositePrimaryKey('usn', 'blogs', blank=True, editable=False, primary_key=True, serialize=False)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog1', to='members.blogs')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members1', to='members.members')),
            ],
        ),
    ]
